regoin = "us-central1"
project_name = "active-sun-337308"
network_name = "gke-network"
public_subnet_name = "managment-subnet"
private_subnet_name = "restricted-subnet"
router_name = "router-gke"
nat_cloud = "nat-gke"
vm_type = "e2-small"
